### ISSUE TITLE
Fix fold plus minus buttons for XML notepad++

### ISSUE THREAD

**Issue by Donaldpherman** [dracula/notepad-plus-plus#22] opened 2019-01-22 20:29 UTC
The buttons for folding are hard to see the difference between + and -.  

![image](https://user-images.githubusercontent.com/3155787/51563406-33aa0a00-1e41-11e9-8243-245502b0f4d3.png)

@ukarim

**Comment by ukarim** [comment] 2019-06-28 15:41
Actually, such behaviour is by design. But it seems that this is not convenient (this is not first issue about folding)

**Comment by ukarim** [comment] 2019-06-28 15:59
![изображение](https://user-images.githubusercontent.com/12429084/60355257-cc941100-99ef-11e9-805c-d416b1994234.png)
Fixed in a latest commit

**Closed by ukarim** 2019-06-28 15:59 UTC
